sudo: false
dist: trusty
language: r
r:
    - 3.5.0

install:
    - bash setup.sh --help
    - bash setup.sh --skip_test 
    - bash setup.sh --skip_test # Running again should do nothing

script:
    - bash setup.sh -b foo/bar 2> err.log || true && grep --silent 'Error' err.log && rm err.log
    - cd test 
    - Rscript testthat.R
    - chmod a+x test_cnv_facets.py && ./test_cnv_facets.py

after_success:
    - Rscript covr.R 
